- hosts: all
  become: true
  gather_facts: true
  tasks:

  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: apache2
      state: present
  
  - name: Install Python
    ansible.builtin.apt:
      name: python
      state: present