- hosts: all
  gather_facts: true
  tasks:

  - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

 - name: Install Python
      raw: apt install python3.8
      when: check_python.rc != 0