---
- hosts: ansibleuser
  become: true
  vars:
    mysql_root_password: omkar
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install MySQL
    apt: 
      name: ['python3-mysqldb'] 
      update_cache: yes 
      cache_valid_time: 3600 
      state: present

  - name: Install MySQL
    apt: 
      name: ['mysql-server'] 
      update_cache: yes 
      cache_valid_time: 3600 
      state: present

  - name: Install PyMySQL
    pip: 
      name: ['pymysql'] 
      state: present

  - name: Start the MySQL service
    service: 
      name: mysql 
      state: started
      enabled: true

  - name: update mysql root password for all root accounts
    mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: ''
      name: 'root'
      password: '{{ mysql_root_password }}'
      state: present