---
- hosts: ansibleuser
  tasks:
  - name: start nginx
    service:
      name: nginx
      state: started

  - name: restart nginx
    service:
      name: nginx
      state: stopped
    become: true
    become_method: sudo